version: '3'

services:
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
        
        
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - postgres
    
networks:
    postgres:
        driver: bridge
        
volumes:
    pg_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "./postgres/data"
            
    pgadmin_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "./pgadmin4/data"
        