version: '3'

services:
    postgres:
        container_name: postgres_container
        image: postgres:${POSTGRESQL_VERSION}
        environment:
            POSTGRES_DB: ${POSTGRESQL_DB}
            POSTGRES_USER: ${POSTGRESQL_USER}
            POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - 5432
        networks:
            - postgres
        restart: unless-stopped
        
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: unless-stopped
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - postgres
    
    
    keycloak:
        container_name: keycloak_container
        image: bitnami/keycloak:${KEYCLOAK_VERSION}
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            #- KEYCLOAK_CREATE_ADMIN_USER=true
            KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
            KEYCLOAK_MANAGEMENT_USER: ${KEYCLOAK_MANAGEMENT_USER}
            KEYCLOAK_MANAGEMENT_PASSWORD: ${KEYCLOAK_MANAGEMENT_PASSWORD}
            KEYCLOAK_DATABASE_HOST: postgres
            KEYCLOAK_DATABASE_PORT: 5432
            KEYCLOAK_DATABASE_NAME: ${POSTGRESQL_DB}
            KEYCLOAK_DATABASE_USER: ${POSTGRESQL_USER}
            KEYCLOAK_DATABASE_PASSWORD: ${POSTGRESQL_PASS}
        depends_on:
            - postgres
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
        